"""Add head_of_household_id to records table

Revision ID: 076beafce6d1
Revises:
Create Date: 2025-07-01 22:45:47.495273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076beafce6d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_of_household_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'records', ['head_of_household_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('head_of_household_id')

    # ### end Alembic commands ###
